// Copyright (c) 2025 yoshinarikamakura
#pragma once
#include <array>
#include <list>
#include <string>
#include <vector>
#include "Definitions.h"
#include "EnergyBand.h"

class FBMC {
// ====== Public interface ======
 public:
// Constructor
//
// === Input ===
//  char* filename ....Input file name
//
    FBMC(std::string param_filename,
          std::string band_filename,
          std::string phonon_filename,
          double temperature,
          std::mt19937& rng);

// Energy from wave vector and band index
// === Input ===
// State ....Wave vector (2*pi/a) and Band index
//
// === Output ===
// double getEnergy ....Carrier energy (eV)
//
    inline double getEnergy(const State s) {
        return carrier_.getEnergy(s);
    }

// Group vlocity from wave vector and band index
//
// === Input ===
// State ....Wave vector (2*pi/a) and Band index
//
// === Output ===
// Vector3 getVelocity ....Group Velocity (m/s)
//
    inline Vector3 getVelocity(const State s) {
        return carrier_.getVelocity(s);
    }

// Select a carrier state randomly on an iso-energy surface
//
// === Input ===
// double energy ....Carrier energy (eV)
// Vector3 r ....Carrier position (m)
//
//  === Output ===
// State selectStateOnIsoEnergySurface ....Carrier state
//
    State selectStateOnIsoEnergySurface(const double energy,
                                        const Vector3 r,
                                        const double charge);

// Carrier free flight
//
// === Input ===
// double dt ....Time step (s)
// Vector3 field ....Electric field (V/m)
// State initial_state ....Carrier state before free flight
//
//  === Output ===
// State flightFree ....Carrier state after free flight
//
    State flightFree(const double dt,
                     const Vector3 field,
                     const State initial_state);

// Carrier scattering
//
// === Input ===
// double dt ....Time step (s)
// State initial_state ....Carrier state before scattering
//
//  === Output ===
// State scatter ....Carrier state after scattering
// int scattering_mechanism ....Scattering mechanism
// std::array<double, 2> eh_pair_energies ....Energies of electron-hole pair
//                                            generated by impact ionization
//                       eh_pair_energies[0] ....Opposite polarity carrier
//                       eh_pair_energies[1] ....Same polarity carrier
//
    State scatter(const double dt,
                  const State initial_state,
                  int& scattering_mechanism,
                  std::array<double, 2>& eh_pair_energies);




    inline double getNumberOfBands(void) {
        return carrier_.getNumberOfBands();
    }

    inline double getBandGapEnergy(void) {
        return EGAP_;
    }

    inline double getPhononEnergy(const State s) {
        return phonon_.getEnergy(s);
    }

    inline double getPhononNumberOfBands(void) {
        return phonon_.getNumberOfBands();
    }



 private:
// ====== Internal Data (Preset parameters) ======

// Directory name of input files
    const std::string TABLE_DIRECTORY_NAME_ = "./inputs/";

// Energy interval for DOSMAX table (eV)
    static constexpr double DELTAE_DOSMAX_ = 0.001;

// (eV)
    static constexpr double EPS_ESCAN_ = 0.01;

// Energy interval for MINMAX table (eV)
    static constexpr double DELTAE_MINMAX_ = 0.01;

// Threshold of infinite roop
    static constexpr int INFINITE_LOOP_THRESHOLD_ = 10000000;

// Minimum energy for scattering rate table (eV);
    static constexpr double MINIMUM_ENERGY_FOR_SCATTERING_RATE_TABLE_ = 0.001;

// Size of scattering rate table
    static constexpr int SIZE_OF_SCATTERING_RATE_TABLE_ = 1000;

//
    static constexpr int NUMBER_OF_SAMPLING_FOR_PH_RATE_TABLE_ = 10;

// ====== Internal Data (Material parameters from input file) ======
// Crystal density (kg/m/m/m)
    double DENSITY_;

// Deformation potential parameter for acoustic phonon (?)
    double ADAC_;

// Deformation potential parameter for acoustic phonon (?)
    double BDAC_;

// Deformation potential parameter for optical phonon (?)
    double ADKOP_;

// Deformation potential parameter for optical phonon (?)
    double BDKOP_;

// Band gap energy (eV)
    double EGAP_;

// Threshold energy of impact ionization (eV)
    double ETHII_;

// Prefactor of impact ionization rate (1/s)
    double SII_;

// Power in Keldysh-like formula of impact ionization ()
    double POWII_;

// Parameter to calculate secondary carrier energy
    double AII1_;

// Parameter to calculate secondary carrier energy
    double BII1_;

// Parameter to calculate secondary carrier energy
    double AII2_;

// Parameter to calculate secondary carrier energy
    double BII2_;

// ====== Internal Data (Objects) ======
    std::mt19937& mt_;
    EnergyBand carrier_;
    EnergyBand phonon_;

// ====== Internal Data ======

// Table of DOSmax
    std::vector<double> dosmax_;

// Size of minmax table
    int NE1_MINMAX_, NE41_MINMAX_;

// Minmax table
    std::vector<std::vector<std::list<std::pair<int, int>>>> minmax_;

// Factor used in carrier free flight
    double FACTOR_FREE_FLIGHT_;

// Thermal energy (eV)
    double THERMAL_ENERGY_;

// ====== Internal methods ======
    void constructDOSTables(std::string band_filename);
    void loadDOSmax(std::string band_filename);
    void makeDOSmaxTable(void);

    void loadMaterialParameter(std::string param_filename);

    void constructPhononScatteringTables(std::string param_filename,
                                         std::string band_filename,
                                         double temperature);

 public:
    double getPhononScatteringRate(const int eta,
                                   const bool isAbsorption,
                                   const State initial_state);

 private:
    State selectStateAfterPhononScattering(const int eta,
                                           const bool isAbsorption,
                                           const State initial_state);

    void loadPhononScatteringRate(std::string band_filename);
    void makePhononScatteringRateTable(void);
    double calculatePhononScatteringRate(const int eta,
                                         const bool isAbsorption,
                                         const State initial_state);
    double getToyMatrixElementForSilicon(State s,
                                         const bool isAbsorption,
                                         const double ei);
    std::vector<std::vector<double>> getMaxToyMatrixElement(const double eimax);

    double getImpactIonizationRate(const State initial_state);
    State selectStateAfterImpactIonization(const State initial_state,
                                       std::array<double, 2>& eh_pair_energies);

    // Table of electron-phonon scattering rate (1/s)
    std::vector<std::vector<double>> phonon_absorption_scattering_rate_table;
    std::vector<std::vector<double>> phonon_emission_scattering_rate_table;

    // Table of Maximum Matrix Elements of Electron-Phonon Scattering (???)
    std::vector<std::vector<double>> matrix_element_max;

    double BETA_;
    double FACTOR_PHONON_SCATTERING_RATE_;
    double ENERGY_GEOMETRIC_RATIO_;
    std::vector<double> hwmax_;
    int SIZE_OF_DOSMAX_TABLE_;
};
